apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  react-pod
  labels:
    name:  react-pod
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  react-pod
    spec:
      containers:
      - image:  akshayraina/image_name:v1.build_number
        name:  react-container
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
      restartPolicy: Always
      imagePullPolicy: Always
