kind: Service
apiVersion: v1
metadata:
  name:  react-service
spec:
  selector:
    app:  react-pod
  type:  LoadBalancer
  ports:
  - name: react-port
    port:  8081
    targetPort:  8080
    nodePort: 31205